# We need to use trusty in order to get libsdl2
sudo: required
dist: xenial
osx_image: xcode11

branches:
  only:
    - master

# 'language: c++' doesn't help us, since it won't use the custom gcc we install
language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev
            - libsdl2-mixer-dev
            - g++-8
            - boost1.67
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'

    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - sdl2
            - sdl2_mixer

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export CC=gcc-8;
      export CXX=g++-8;
    fi

before_script:
  - (mkdir build_dbg && cd build_dbg && cmake .. -DCMAKE_BUILD_TYPE=Debug)
  - (mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release)

script:
  - (cd build_dbg && make -j2 && ctest)
  - (cd build && make -j2 && ctest)
